apiVersion: v1  # Specifies the API version for the Service
kind: Service  # Defines the type of resource, in this case, a Service
metadata:
  name: auth  # The name of the Service
spec:
  selector:
    app: auth  # Selects pods with the label "app: auth" (as mentioned in the auth-deploy.yaml) to be managed by this Service
  type: ClusterIP  # The type of Service, which exposes the service on an internal IP in the cluster
  ports:
    - port: 5000  # The port that the Service will expose
      targetPort: 5000  # The port on the pod that the Service should forward traffic to
      protocol: TCP  # The protocol used for the Service
