apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-microservice
  template:
    metadata:
      labels:
        app: auth-microservice
    spec:
      containers:
      - name: auth-microservice
        image: saifsaifee/auth-mp4-to-mp3-microservice:latest
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: MYSQL_HOST
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DB
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: MYSQL_DB
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: MYSQL_PORT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: JWT_SECRET
